version: "3.1"

services:
  app:
    image: ./Dockerfile
    environment:
      PORT: ${PORT}
    depends_on:
      - db 
    volumes:
      - "$(pwd):/app"
      - /app/node_modules

  db:
    image: postgres:14
    container_name: pisonitsha-backend
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
